name: timetable
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  http: ^0.13.4
  date_format: ^2.0.5
  shared_preferences: ^2.0.5
  curved_navigation_bar: ^1.0.3
  animated_text: ^1.0.2
  animated_text_kit: ^3.1.2
  dart_date: ^1.0.9
  animated_widgets: ^1.0.6


  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  dev: ^1.0.0
  json_serializable: ^6.5.3

dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  freezed_annotation: ^2.2.0
  theme_tailor: ^1.0.6
  theme_tailor_annotation: ^1.0.3

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets\ic_launcher.png
    - assets\logo.png

